version: '3'
services:
    db:
        image: mysql:5.7
        container_name: mysql
        ports:
            - "33:3306"
        #environment:
        #    - "MYSQL_ROOT_PASSWORD=123456"
        env_file: 83-common.env