version: '3'
services:
    web:
        container_name: nginxnet1
        ports:
            - "2727:80"
        image: httpd
        networks:
            - "net-test"
    web2:
        container_name: nginxnet2
        ports:
            - "2828:80"
        image: httpd
        networks:
            - "net-test"
networks:
    net-test:
