version: '3'
services:
    web:
        container_name: nginx2
        ports:
           - "7272:80"
        image: httpd
        networks:
          - net-test
    web2:
        container_name: nginx3
        ports:
          - "7373:80"
        image: httpd
        networks:
          - net-test
networks:
    net-test:
