version:    '3'
services:
    web:
        container_name: "nginx"
        ports:
            -   "9090:80"
        volumes:
            -   "vol2:/usr/share/nginx/html"
        image:  nginx
volumes:
    vol2:
